### ISSUE TITLE
CS2 demo support?

### ISSUE THREAD

**Issue by NorskNoobing** [jayden-chan/puggies#59]
I was wondering if this is going to get CS2 support? I'm unsure of all of the changes to demos in CS2, but the demos won't scan because of the file validation:
```
2024-09-24T05:52:03.710842125Z [puggies-core] 2024/09/24 05:52:03 [info] new file detected: /demos/${DEMO_FILENAME}
2024-09-24T05:52:03.711577047Z [puggies-core] 2024/09/24 05:52:03 [error] demo=${DEMO_FILENAME} Failed to parse demo: invalid File-Type; expecting HL2DEMO in the first 8 bytes (ErrInvalidFileType)
```

This would be fixed by replacing `HL2DEMO` with `PBDEMS2` in the file validation, but there could be other breaking changes that I don't know of.

**Comment by jayden-chan** [comment]
Hey there,

Unfortunately this project is no longer maintained and I don't have any plans to resurrect it because I no longer have a use for it. I apologize for any time you may have wasted trying to get it set up with the incomplete/incorrect docs.

The demo parsing library used by the server is [demoinfocs-golang](https://github.com/markus-wa/demoinfocs-golang) and it looks like the newer versions of it support CS2 demos. It might not be too much work to update Puggies to support CS2 demos, although I haven't looked at the updated library docs in detail so I'm not sure.

I am going to archive this repo as I will not be developing the project anymore. Any further development will need to be done by someone else in a fork.

Thanks for your interest in the project and good luck.
